
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mysql:
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alert_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mysql
      - mailhog
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DB_URL=jdbc:mysql://localhost:8080/alert_system
      - MAILHOG_HOST=mailhog
      - MAILHOG_PORT=1025
    command: [ "java", "-cp", "target/Projet_CCSR_2025-1.0-SNAPSHOT.jar","ci.cssr.router"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
